/*
 * CSVDatabase.h
 *
 *  Created on: Jul 16, 2014
 *      Author: wzw7yn
 */

#ifndef CSVDATABASE_H_
#define CSVDATABASE_H_

#include "DBDefines.h"
#include "MetadataObject.h"

namespace simplearchive {
/**
 * @brief This is the main interface into the CSV Database. This Database is used
 * to create a Comma Separated Value based database.
 * The created files in the database are stored in the data folder of image set folder.
 * this will the limit the resulting files to a manageable size.
 * so that the metadata records are also a manageable length, the matedata is spit up
 * into sections. each section it  associated by a unique sequence number. This sequence
 * number is generated by other the SQL database or this database if the SQL one is not enabled.
 */
class FolderSetList;
class CSVDatabase {
	CSVDatabase();
	static CSVDatabase *m_this;
public:
	static CSVDatabase &get();
	virtual ~CSVDatabase();
	void add(MetadataObject &metadataObject, const char *path);
	void update(MetadataObject &metadataObject, unsigned int idx, const char *path);
	const MetadataObject *get(unsigned int idx, const char *path);
};

} /* namespace simplearchive */
#endif /* CSVDATABASE_H_ */
